version: '2'
services:

  ptb220:
    privileged: true
    build: ./PTB220
    restart: on-failure

  ptu300:
    privileged: true
    build: ./PTU300
    restart: on-failure

  windsonic:
    privileged: true
    build: ./WINDSONIC
    restart: on-failure

  raingauge:
    privileged: true
    build: ./RAINGAUGE
    restart: on-failure

  rainfall:
    build: ./rainfall
    restart: always

  aws_iot:
    build: ./aws_iot
    restart: on-failure

  metoffice_wow:
    build: ./metoffice_wow
    restart: on-failure

  wx_underground:
    build: ./wx_underground
    restart: on-failure

  corlysis:
    build: ./corlysis
    restart: on-failure

  test_svc:
    build: ./test_svc
    restart: always
    depends_on:
      - ptb220
      - ptu300
      - raingauge
      - rainfall
      - windsonic

  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
